config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:index,:create,:new] do
    resources :comments, only: [:new,:create,:show,:edit,:update,:destroy]
  end
  resources :subs do
    resources :posts, only: [:new,:create]
  end
  resources :users, only: [:new,:create]
  resource :session, only: [:new,:create,:destroy]

  root 'subs#index'
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :text             not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :description, presence: true

    belongs_to :moderator,
        foreign_key: :moderator_id,
        class_name: :User
    has_many :posts
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: %i[ show edit update destroy ]
  before_action :require_logged_in!, only: %i[new create]
  before_action :require_moderator!, only: %i[edit update destroy]

  # GET /subs or /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1 or /subs/1.json
  def show
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
  end

  # POST /subs or /subs.json
  def create
    @sub = current_user.subs.new(sub_params)

    respond_to do |format|
      if @sub.save
        format.html { redirect_to sub_url(@sub), notice: "Sub was successfully created." }
        format.json { render :show, status: :created, location: @sub }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subs/1 or /subs/1.json
  def update
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to sub_url(@sub), notice: "Sub was successfully updated." }
        format.json { render :show, status: :ok, location: @sub }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1 or /subs/1.json
  def destroy
    @sub.destroy

    respond_to do |format|
      format.html { redirect_to subs_url, notice: "Sub was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_params
      params.require(:sub).permit(:title, :description, :moderator_id)
    end
    
    def require_moderator!
      return if current_user.id == @sub.moderator_id
      redirect_to subs_url
    end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<%= form_with(model: sub) do |form| %>
  <% if sub.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
        <% sub.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subs/_sub.html.erb
<div id="<%= dom_id sub %>">
  <p>
    <strong>Title:</strong>
    <%= sub.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= sub.description %>
  </p>

  <p>
    <strong>Moderator:</strong>
    <%= sub.moderator_id %>
  </p>

</div>

app/views/subs/edit.html.erb
<h1>Editing sub</h1>

<%= render "form", sub: @sub %>

<br>

<div>
  <%= link_to "Show this sub", @sub %> |
  <%= link_to "Back to subs", subs_path %>
</div>

app/views/subs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>FakeReddit</h1>

<div id="subs">
  <% @subs.each do |sub| %>
    <div class="link">
      <div class="title"><%= link_to sub.title, sub %></div>
    </div>
      <div class="tagline"><%= sub.description %></div>
      <br>
  <% end %>
</div>

<div class="morelink"><%= link_to "Create a new Subreddit", new_sub_path %></div>

app/views/subs/new.html.erb
<h1>New sub</h1>

<%= render "form", sub: @sub %>

<br>

<div>
  <%= link_to "Back to subs", subs_path %>
</div>

app/views/subs/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @sub.title %></h1>
<h5><%= @sub.description %></h5>
<br>
<div>
<% @sub.posts.each do |post| %>
  <%= link_to "#{post.title} by: #{post.author.name}" , post_path(post) %>
<% end %>
</div>
<br>
<div>
  <p>
    <%= link_to "Submit a Post", new_sub_post_url(@sub) %>
  </p>
</div>
<br>
<div>
  <% if current_user %>
    <% if current_user.is_moderator?(@sub) %>
      <%= link_to "Edit this sub", edit_sub_path(@sub) %> |
    <% end %>

    <% if current_user.is_moderator?(@sub) %>
      <%= button_to "Destroy this sub", @sub, method: :delete %>
    <% end %>
  <% end %>
  <%= link_to "Return to Homepage", subs_path %>
</div>