config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:index,:create,:new] do
    resources :comments, only: [:new,:create,:show,:edit,:update,:destroy]
  end
  resources :subs do
    resources :posts, only: [:new,:create]
  end
  resources :users, only: [:new,:create]
  resource :session, only: [:new,:create,:destroy]

  root 'subs#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, presence: true

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User

    belongs_to :sub

    has_many :comments,
        class_name: :Comment,
        foreign_key: :post_id

    def comments_by_parent
        comments_by_parent = Hash.new { |hash, key| hash[key] = [] }
    
        self.comments.includes(:author).each do |comment|
            comments_by_parent[comment.parent_comment_id] << comment
        end
    
        comments_by_parent
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :is_author, only: %i[edit update destroy]
  before_action :set_sub, except: %i[show]

   # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)
    @post.sub_id = @sub.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to sub_post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to sub_post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to sub_url(@sub), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :url, :content, :sub_id, :author_id)
    end

    def is_author
      return if current_user == @post.author
      redirect_to sub_url(@post.sub)
    end

    def set_sub
      @sub = Sub.find(params[:sub_id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@sub,post]) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= post.url %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Sub:</strong>
    <%= post.sub_id %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= post.author_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to Subreddit", sub_path(@sub) %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @post.title %></h1>
<h4><%= @post.content %></h4>
<div>By: <%= @post.author.name %> </div>

<br>

<h3>Comments:</h3>
<% @post.comments.each do |com| %>
<div><%= link_to com.content, post_comment_url(@post,com) %></div>
<% end %>

<div><%= link_to "Post a new comment", new_post_comment_url(@post) %></div>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Return to Subreddit", sub_path(@post.sub) %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>